
"use client";

import { useState } from "react";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle, 
  DialogDescription,
  DialogFooter
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { assignmentBreakdownTool, AssignmentBreakdownOutput } from "@/ai/flows/assignment-breakdown-tool";
import { Sparkles, Loader2, ListChecks, ArrowRight, Tool } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";

interface AiBreakdownDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  description: string;
}

export function AiBreakdownDialog({ open, onOpenChange, description }: AiBreakdownDialogProps) {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<AssignmentBreakdownOutput | null>(null);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const output = await assignmentBreakdownTool({ description });
      setResult(output);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 font-headline text-2xl">
            <Sparkles className="h-6 w-6 text-primary" />
            AI Study Breakdown
          </DialogTitle>
          <DialogDescription>
            Gemini will analyze your assignment and create a step-by-step action plan.
          </DialogDescription>
        </DialogHeader>

        {!result && !loading && (
          <div className="py-8 text-center space-y-4">
            <div className="bg-muted p-4 rounded-xl text-left italic text-sm">
              "{description}"
            </div>
            <Button onClick={handleGenerate} className="shadow-lg shadow-primary/20">
              Generate Action Plan
            </Button>
          </div>
        )}

        {loading && (
          <div className="flex flex-col items-center justify-center py-20 gap-4">
            <Loader2 className="h-10 w-10 text-primary animate-spin" />
            <p className="text-muted-foreground animate-pulse">Consulting Gemini for the best approach...</p>
          </div>
        )}

        {result && (
          <ScrollArea className="flex-1 pr-4">
            <div className="space-y-6 py-4">
              {result.actionPlan.map((task, idx) => (
                <div key={idx} className="bg-card border rounded-xl p-5 shadow-sm space-y-3">
                  <div className="flex items-center gap-3">
                    <span className="flex items-center justify-center w-6 h-6 rounded-full bg-primary text-primary-foreground text-xs font-bold">
                      {idx + 1}
                    </span>
                    <h4 className="font-bold text-lg">{task.title}</h4>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed pl-9">
                    {task.details}
                  </p>
                  {task.recommendedTools && task.recommendedTools.length > 0 && (
                    <div className="flex flex-wrap gap-2 pl-9">
                      {task.recommendedTools.map((tool, tIdx) => (
                        <Badge key={tIdx} variant="secondary" className="text-[10px] font-medium uppercase tracking-wide">
                          {tool}
                        </Badge>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </ScrollArea>
        )}

        <DialogFooter className="sm:justify-start">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          {result && (
            <p className="text-[10px] text-muted-foreground mt-2 sm:mt-0 italic flex items-center gap-1">
              Generated by Assigno AI
            </p>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
